app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::group(['middleware' => ['web']], function () {

	Route::auth();
	Route::get('auth/verify/{token}', 'Auth\AuthController@verify');
	Route::get('auth/send-verification', 'Auth\AuthController@sendVerification');

	Route::get('/', 'DashboardsController@index');
	Route::get('/dashboards', 'DashboardsController@index');

	Route::get('/calendars', 'CalendarsController@index');

	Route::get('/find-me', 'FindMeController@index');

	Route::post('users/toogle-status', 'UsersController@toogleStatus');
	Route::resource('users', 'UsersController');

	Route::get('/declare-projects', 'DeclareProjectsController@index');
	Route::get('/declare-projects/create', 'DeclareProjectsController@create');
	Route::post('/declare-projects', 'DeclareProjectsController@store');
	Route::get('/declare-projects/{id}', 'DeclareProjectsController@show');
	Route::get('/declare-projects/{id}/edit', 'DeclareProjectsController@edit');
	Route::patch('/declare-projects/{id}', 'DeclareProjectsController@update');

	Route::get('/cab-projects', 'CabProjectsController@index');
	Route::get('/cab-projects/{development_id}/create', 'CabProjectsController@create');
	Route::post('/cab-projects/{development_id}', 'CabProjectsController@store');
	Route::get('/cab-projects/{development_id}', 'CabProjectsController@show');
	Route::get('/cab-projects/{development_id}/edit', 'CabProjectsController@edit');
	Route::patch('/cab-projects/{development_id}', 'CabProjectsController@update');

	Route::get('/post-projects', 'PostProjectsController@index');
	Route::get('/post-projects/{development_id}/create', 'PostProjectsController@create');
	Route::post('/post-projects/{development_id}', 'PostProjectsController@store');
	Route::get('/post-projects/{development_id}', 'PostProjectsController@show');
	Route::get('/post-projects/{development_id}/edit', 'PostProjectsController@edit');
	Route::patch('/post-projects/{development_id}', 'PostProjectsController@update');

	//Updated on 2016-12-26 by hsbakbr
	Route::get('/activity', 'ActivityController@index');
	Route::get('/activity/{development_id}', 'ActivityController@monitoring');
        Route::get('/activity/{development_id}/edit', 'ActivityController@edit');
        Route::get('/activity/{development_id}/delete', 'ActivityController@delete');
        Route::post('/activity/process' , 'ActivityController@process');
        Route::post('/activity/delete' , 'ActivityController@delete');

        Route::get('/offers/{offer_id}', 'OffersController@index');
        Route::get('/compare/', 'OffersController@compare');
        Route::post('/compare/', 'OffersController@show');
        Route::post('/compare/search', 'OffersController@search');
    
        Route::get('/find-me', 'FindMeController@index');
        Route::post('/find-me', 'FindMeController@search');

	//testing API
	Route::get('/check-profile', 'TestingController@index');
	Route::get('/testing2', 'TestingControler2@index');	
	Route::get('/check-profile', 'CheckProfileController@index');
	Route::post('/check-profile', 'CheckProfileController@search');


});

app/Models/User.php
<?php

namespace App\Models;

use Mail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Zizaco\Entrust\Traits\EntrustUserTrait;

class User extends Authenticatable
{
    use EntrustUserTrait;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'users';
    protected $fillable = [
        'name',
        'email',
	'username',
        'verification_token',
        'is_verified',
        'is_active',
        'last_login',
        'avatar',
        'remember_token'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'remember_token',
    ];

    protected $casts = [
        'is_verified' => 'boolean',
    ];

    /**
     * Relationship
     */
    
    public function declareProjecs()
    {
        return $this->hasMany(DeclareProject::class);
    }

    public function cabProjecs()
    {
        return $this->hasMany(CabProject::class);
    }

    public function postProjecs()
    {
        return $this->hasMany(PostProject::class);
    }


    /**
     * Methods
     */

    public function hasPassword() {
        return $this->password !== '';
    }

    public function generateVerificationToken()
    {
        $token = $this->verification_token;

        if (!$token) {
            $token = str_random(40);
            $this->verification_token = $token;
            $this->save();
        }

        return $token;
    }

    public function sendVerification()
    {
        $token = $this->generateVerificationToken();

        $user = $this;
        
        Mail::queue('auth.emails.verification', compact('user', 'token'), function ($m) use ($user) {
              $m->to($user->email, $user->name)->subject('Zoro Account Verification');
        }); 
    }

    public function verify() {
        $this->is_verified = 1;
        $this->verification_token = null;
        $this->save();
    }

    public function isAdmin()
    {
        return $this->hasRole('admin');
    }

    public function syncRoles()
    {
        $roles = array();

        if (request()->has('roles')) {
            foreach (request()->input('roles') as $role)
            {
                array_push($roles, $role);
            }
        }

        $this->roles()->sync($roles);
    }

    public static function statusList() {
        return [
            '' => 'Select Status',
            '1' => 'Active',
            '0' => 'Not Active',
        ];
    }

    public static function verifiedStatusList() {
        return [
            '' => 'Select Status',
            '1' => 'Verified',
            '0' => 'Not Verified',
        ];
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Flash;
use App\Models\User;
use App\Http\Requests;
use Illuminate\Http\Request;

class UsersController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('role:admin');
    }

    public function index(Request $request)
    {
    	$q = $request->get('q');

    	$users = User::with('roles')->where('name', 'LIKE', '%'.$q.'%')->paginate(10);

        return view('users.index', compact('users', 'q'));
    }

    public function create()
    {
    	$user = new User;

    	return view('users.create', compact('user'));
    }

    public function store(Request $request)
    {
    	$this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
	    'username' => 'required',
            'is_verified' => 'required',
            'is_active' => 'required',
            'avatar' => 'mimes:jpeg,png,jpg',
        ]);

        $avatar = '';
        if ($request->hasFile('avatar')) {
            $avatar = $this->uploadAvatar();
        }

        $user = new User;
        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->password = bcrypt('dummy');
	$user->username = $request->input('username');
        $user->is_verified = $request->input('is_verified');
        $user->is_active = $request->input('is_active');
        $user->avatar = $avatar;
        $user->save();

        $user->syncRoles();

        \Flash::success('Create new user success');

        return redirect()->route('users.index');
    }

    public function show($id)
    {
    	$user = User::with(['roles'])->where('id', $id)->first();

        if (! $user) {
        	Flash::error('User not found!');
        	return redirect()->back();
        }

        return view('users.details', compact('user'));
    }

    public function edit($id)
    {
    	$user = User::with(['roles'])->where('id', $id)->first();

        if (! $user) {
        	Flash::error('User not found!');
        	return redirect()->back();
        }

        return view('users.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
    	$this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users,email,'. $id,
	    'username'=> 'required',
            'is_verified' => 'required',
            'is_active' => 'required',
            'avatar' => 'mimes:jpeg,png,jpg',
        ]);

    	$user = User::where('id', $id)->first();

    	if (! $user) {
        	Flash::error('User not found!');
        	return redirect()->back();
        }

        $avatar = $user->avatar;
        if ($request->hasFile('avatar')) {
            $avatar = $this->uploadAvatar();
        }

        $user->name = $request->input('name');
        $user->email = $request->input('email');
        $user->is_verified = $request->input('is_verified');
	$user->username = $request->input('username');
        $user->is_active = $request->input('is_active');
        $user->avatar = $avatar;
        $user->save();

        $user->syncRoles();

        \Flash::success('Update new user success');

        return redirect('/users/'.$user->id);
    }

    public function toogleStatus(Request $request)
    {
        $id = $request->input('id');
        $status = $request->input('status');

        $user = User::where('id', $id)->first();

        if (! $user) {
        	Flash::error('User not found!');
        	return redirect()->back();
        }

        $user->is_active = $status;
        $user->save();

        if ($status == 1) {
            $message = 'User successfully activated.';
        } elseif ($status == 0) {
            $message = 'User successfully deactivated.';
        }

        Flash::success($message);

        return redirect()->back();
    }

    public function uploadAvatar()
    {
    	$img = request()->file('avatar');

        $fileName = str_random(40) . '.' . $img->guessClientExtension();
        $destinationPath = public_path() . '/img/avatars/';
        $img->move($destinationPath, $fileName);

        return env('APP_URL').'/img/avatars/'.$fileName;
    }
}

resources/views/users/_form.blade.php
@if ($user->id !== null)
<div class="form-group {!! $errors->has('id') ? 'has-error' : '' !!}">
	{!! Form::label('id', 'User ID') !!}
	{!! Form::text('id', $user->id, ['class'=>'form-control', 'disabled']) !!}
	{!! $errors->first('id', '<p class="help-block">:message</p>') !!}
</div>
@endif

<div class="form-group {!! $errors->has('name') ? 'has-error' : '' !!}">
	{!! Form::label('name', 'Name') !!}
	{!! Form::text('name', null, ['class'=>'form-control']) !!}
	{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
	{!! Form::label('email', 'Email') !!}
	{!! Form::text('email', null, ['class'=>'form-control']) !!}
	{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('username') ? 'has-error' : '' !!}">
    {!! Form::label('username', 'User LDAP') !!}
    {!! Form::text('username', null, ['class'=>'form-control']) !!}
    {!! $errors->first('username', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
	{!! Form::label('roles', 'Roles') !!}
	
	{!! Form::select('roles[]',
		App\Models\Role::lists('name','id')->all(),
		array_keys($user->roles()->lists('name','id')->toArray()),
		['id'=>'roles', 'class'=>'form-control', 'multiple']) !!}

</div>

<div class="form-group {!! $errors->has('is_verified') ? 'has-error' : '' !!}">
	{!! Form::label('is_verified', 'Verified Status') !!}
	{!! Form::select('is_verified', App\Models\User::verifiedStatusList(), null, ['id'=>'verified_list', 'class'=>'form-control']) !!}
	{!! $errors->first('is_verified', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('is_active') ? 'has-error' : '' !!}">
	{!! Form::label('is_active', 'Status') !!}
	{!! Form::select('is_active', App\Models\User::statusList(), null, ['id'=>'status_list', 'class'=>'form-control']) !!}
	{!! $errors->first('is_active', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('avatar') ? 'has-error' : '' !!}">
	{!! Form::label('avatar', 'Avatar') !!}
	{!! Form::file('avatar') !!}
	{!! $errors->first('avatar', '<p class="help-block">:message</p>') !!}
</div>

@if ($user->avatar != null)
	<div class="form-group">
		<label for="items_serial_number">Current Avatar: </label>
		<br>
		<div class="row">
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="{{ $user->avatar }}" style="width: 200px; height: 200px;">
				</div>
			</div>
		</div>
	</div>
@endif

@section('raw-script')

    <script type="text/javascript">

        $('#status_list').select2({
            'placeholder':'Pilih Status',
        });

        $('#verified_list').select2({
            'placeholder':'Pilih Verified Status',
        });

        $('#roles').select2({
            'placeholder':'Select roles...',
            tags:true,
            multiple: true
        });

    </script>
@endsection

resources/views/users/bck_form.blade.php
@if ($user->id !== null)
<div class="form-group {!! $errors->has('id') ? 'has-error' : '' !!}">
	{!! Form::label('id', 'User ID') !!}
	{!! Form::text('id', $user->id, ['class'=>'form-control', 'disabled']) !!}
	{!! $errors->first('id', '<p class="help-block">:message</p>') !!}
</div>
@endif

<div class="form-group {!! $errors->has('name') ? 'has-error' : '' !!}">
	{!! Form::label('name', 'Name') !!}
	{!! Form::text('name', null, ['class'=>'form-control']) !!}
	{!! $errors->first('name', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('email') ? 'has-error' : '' !!}">
	{!! Form::label('email', 'Email') !!}
	{!! Form::text('email', null, ['class'=>'form-control']) !!}
	{!! $errors->first('email', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('password') ? 'has-error' : '' !!}">
    {!! Form::label('password', 'Password') !!}
        {!! Form::password('password', ['class'=>'form-control']) !!}
    {!! $errors->first('password', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('password_confirmation') ? 'has-error' : '' !!}">
    {!! Form::label('password_confirmation', 'Confirm Password') !!}
        {!! Form::password('password_confirmation', ['class'=>'form-control']) !!}
    {!! $errors->first('password_confirmation', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group">
	{!! Form::label('roles', 'Roles') !!}
	
	{!! Form::select('roles[]',
		App\Models\Role::lists('name','id')->all(),
		array_keys($user->roles()->lists('name','id')->toArray()),
		['id'=>'roles', 'class'=>'form-control', 'multiple']) !!}

</div>

<div class="form-group {!! $errors->has('is_verified') ? 'has-error' : '' !!}">
	{!! Form::label('is_verified', 'Verified Status') !!}
	{!! Form::select('is_verified', App\Models\User::verifiedStatusList(), null, ['id'=>'verified_list', 'class'=>'form-control']) !!}
	{!! $errors->first('is_verified', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('is_active') ? 'has-error' : '' !!}">
	{!! Form::label('is_active', 'Status') !!}
	{!! Form::select('is_active', App\Models\User::statusList(), null, ['id'=>'status_list', 'class'=>'form-control']) !!}
	{!! $errors->first('is_active', '<p class="help-block">:message</p>') !!}
</div>

<div class="form-group {!! $errors->has('avatar') ? 'has-error' : '' !!}">
	{!! Form::label('avatar', 'Avatar') !!}
	{!! Form::file('avatar') !!}
	{!! $errors->first('avatar', '<p class="help-block">:message</p>') !!}
</div>

@if ($user->avatar != null)
	<div class="form-group">
		<label for="items_serial_number">Current Avatar: </label>
		<br>
		<div class="row">
			<div class="col-md-3">
				<div class="thumbnail">
					<img src="{{ $user->avatar }}" style="width: 200px; height: 200px;">
				</div>
			</div>
		</div>
	</div>
@endif

@section('raw-script')

    <script type="text/javascript">

        $('#status_list').select2({
            'placeholder':'Pilih Status',
        });

        $('#verified_list').select2({
            'placeholder':'Pilih Verified Status',
        });

        $('#roles').select2({
            'placeholder':'Select roles...',
            tags:true,
            multiple: true
        });

    </script>
@endsection

resources/views/users/create.blade.php
@extends('layouts.app')

@section('breadcrumb')
	<div class="row wrapper border-bottom white-bg page-heading">
	    <div class="col-lg-10">
	        <h2></h2>
	        <ol class="breadcrumb">
	            <li>
	                <a href="/">Home</a>
	            </li>
	            <li class="active">
                    <a href="/users">Users</a>
	            </li>
                <li class="active">
                    <strong>Create</strong>
                </li>
	        </ol>
	    </div>
	</div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Create new user</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    {!! Form::model($user, ['url' => url('/users'), 'files' => true])!!}
                        
                        @include('users._form', ['model' => $user]) 
                        
                        <br>

                        <div class="form-group">    
                            <button type="submit" id="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i> Save
                            </button>
                        </div>

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/details.blade.php
@extends('layouts.app')

@section('breadcrumb')
	<div class="row wrapper border-bottom white-bg page-heading">
	    <div class="col-lg-10">
	        <h2></h2>
	        <ol class="breadcrumb">
	            <li>
	                <a href="/">Home</a>
	            </li>
	            <li class="active">
                    <a href="/users">Users</a>
                </li>
                <li class="active">
                    <strong>Details</strong>
                </li>
	        </ol>
	    </div>
	</div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>POST Project Details</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    <div class="form-group">    
                        <a class="btn btn-info" href="{{ route('users.edit', $user->id)}}"><i class="fa fa-edit"></i> Edit</a>
                    </div>

                    <div class="form-group">
                        {!! Form::label('name', 'Name') !!}
                        {!! Form::text('name', $user->name, ['class'=>'form-control', 'disabled']) !!}
                    </div>
                    
                    <div class="form-group">
                        {!! Form::label('email', 'Email') !!}
                        {!! Form::text('email', $user->email, ['class'=>'form-control', 'disabled']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('roles', 'Roles') !!}
                        
                        {!! Form::select('roles[]',
                            ['0'=>'No Roles']+App\Models\Role::lists('name','id')->all(),
                            array_keys($user->roles()->lists('name','id')->toArray()),
                            ['id'=>'roles', 'class'=>'form-control', 'multiple', 'disabled']) !!}

                    </div>

                    <div class="form-group">
                        {!! Form::label('is_verified', 'Verified') !!}
                        {!! Form::text('is_verified', ($user->is_verified == 1) ? 'Yes' : 'No' , ['class'=>'form-control', 'disabled']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('is_active', 'Status') !!}
                        {!! Form::text('is_active', ($user->is_active == 1) ? 'Active' : 'Not Active' , ['class'=>'form-control', 'disabled']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('last_login', 'Last Login') !!}
                        {!! Form::text('last_login', $user->last_login, ['class'=>'form-control', 'disabled']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('avatar', 'Avatar') !!} <br>
                        @if ($user->avatar != null)
                            <img src="{{ $user->avatar }}" alt="" style="width: 150px;">
                        @else
                            {!! Form::text('avatar', 'Does not have avatar', ['class'=>'form-control', 'disabled']) !!}
                        @endif
                    </div>

                    <div class="form-group">
                        {!! Form::label('created_at', 'Created At') !!}
                        {!! Form::text('created_at', $user->created_at, ['class'=>'form-control', 'disabled']) !!}
                    </div>

                    <div class="form-group">
                        {!! Form::label('updated_at', 'Updated At') !!}
                        {!! Form::text('updated_at', $user->updated_at, ['class'=>'form-control', 'disabled']) !!}
                    </div>

                    <div class="form-group">    
                        <a class="btn btn-info" href="{{ route('users.edit', $user->id)}}"><i class="fa fa-edit"></i> Edit</a>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('raw-script')

    <script type="text/javascript">

        $('#roles').select2({
            'placeholder':'Select roles...',
            tags:true,
            multiple: true
        });

    </script>
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('breadcrumb')
	<div class="row wrapper border-bottom white-bg page-heading">
	    <div class="col-lg-10">
	        <h2></h2>
	        <ol class="breadcrumb">
	            <li>
	                <a href="/">Home</a>
	            </li>
	            <li class="active">
                    <a href="/users">Users</a>
                </li>
                <li class="active">
                    <strong>Edit</strong>
                </li>
	        </ol>
	    </div>
	</div>
@endsection

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>Edit User</h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">

                    {!! Form::model($user, ['url' => url('/users/'.$user->id), 'method' => 'patch' , 'files' => true])!!}
                        
                        @include('users._form', ['model' => $user]) 

                        <br>
                        <div class="form-group">    
                            <button type="submit" id="submit" class="btn btn-primary">
                                <i class="fa fa-save"></i> Save
                            </button>
                        </div>

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('breadcrumb')
	<div class="row wrapper border-bottom white-bg page-heading">
	    <div class="col-lg-10">
	        <h2></h2>
	        <ol class="breadcrumb">
	            <li>
	                <a href="/">Home</a>
	            </li>
	            <li class="active">
	                <strong>Users</strong>
	            </li>
	        </ol>
	    </div>
	</div>
@endsection

@section('content')
	<div class="row">
        <div class="col-lg-12 col-md-6">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>All Users </h5>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
					
                    <h3>
                        <small>
                            <a href="{{ route('users.create') }}" class="btn btn-warning"> <i class="fa fa-plus-circle"></i> Tambah Users</a>
                        </small>
                    </h3>
                    
                    {!! Form::open(['url' => 'users', 'method'=>'get', 'class'=>'form-inline'])!!}
                        <div class="form-group {!! $errors->has('q') ? 'has-error' : '' !!}">
                            {!! Form::text('q', isset($q) ? $q : null, ['class'=>'form-control', 'placeholder' => 'Cari berdasarkan nama...']) !!}
                            {!! $errors->first('q', '<p class="help-block">:message</p>') !!}
                        </div>
                        {!! Form::submit('Cari', ['class'=>'btn btn-primary']) !!}
                    {!! Form::close() !!}

                    @include('layouts._show-all-data', ['url' => '/users'])

                    <br>
                    <div class="table-responsive">
                        <table class="table table-bordered table-hover white-bg">
                            <thead>
                                <tr>
                                    <th class="active">#ID</th>
                                    <th class="active">Name</th>
                                    <th class="active">Email</th>
                                    <th class="active">Status</th>
                                    <th class="active">Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse($users as $user)
                                <tr>
                                    <td>{{ $user->id }}</td>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                        @if ($user->is_active)
                                            <span class="text-info">
                                                Active
                                            </span>
                                        @else
                                            <span class="text-danger">
                                                Not Active
                                            </span>
                                        @endif
                                    </td>
                                    <td>
                                        {!! Form::open(['url' => 'users/toogle-status', 'class' => 'form-inline', 'method' => 'post'] ) !!}
                                            
                                            <a class="btn btn-xs btn-success" href="{{ route('users.show', $user->id)}}"><i class="fa fa-eye"></i> Details</a>
                                            <a class="btn btn-xs btn-warning" href="{{ route('users.edit', $user->id)}}"><i class="fa fa-edit"></i> Edit</a>

                                            <input type="hidden" name="id" value="{{$user->id}}">

                                            @if ($user->is_active == 1)
                                                <input type="hidden" name="status" value="0">
                                                <button type="submit" class="btn btn-xs btn-danger js-submit-confirm" data-confirm-message="Are you sure to deactivate this account ?">
                                                    <i class="fa fa-trash"> Deactivate</i>
                                                </button>
                                            @elseif ($user->is_active == 0)
                                                <input type="hidden" name="status" value="1">
                                                <button type="submit" class="btn btn-xs btn-info js-submit-confirm" data-confirm-message="Are you sure to activate this account ?">
                                                    <i class="fa fa-check"> Activate</i>
                                                </button>
                                            @endif

                                        {!! Form::close()!!}
                                    </td>
                                </tr>
                                @empty
                                <tr>
                                    <td colspan="4">Tidak ada data users.</td>
                                </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

@section('raw-script')

    <script type="text/javascript">



    </script>

@endsection